# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

julia:
  - 0.6
  - nightly

os:
  - linux

notifications:
  email: false

#matrix:
#  allow_failures:
#    - julia: nightly

addons:
  apt:
    packages:
      - gnuplot

after_success:
  # push coverage results to Coveralls
  # - julia -e 'cd(Pkg.dir("dummy")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  # - julia -e 'cd(Pkg.dir("dummy")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
